#server:
#  port: 1234
#
#spring: 
#  datasource:
#    url: jdbc:mysql://expensedbinstance.ccaptx9am8op.ap-south-1.rds.amazonaws.com:3306/expense 
#    username: yogeshchacherkar 
#    password: password
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8722/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
#spring:
#  application:
#    name: ExpenseClaimDetailsModule-gateway
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#logging:
#  level:
#    com.example.howtodoinjava: DEBUG